=== huson2012/aionknight/gameserver/data/static_data/player_experience_table.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--

	Назначение файла	:
	Ревизия				: 1.0.1 (Beta)
	Версия клиента		: 2.5 (Иннова)

 -->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="player_experience_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="exp" type="xs:long" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huson2012/aionknight/trunk/gameserver/data/static_data/player_experience_table.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

	Назначение файла: Настройка уровней в зависимости от кол-ва 'EXP'
	=================================================================
	Версия сервера: Aion-Knight 2.7 (Beta version)
	Версия клиента: 2.7 (Иннова)
	=====================================================================
	Разработка серверной части: Copyright (c) Aion-Knight, 2011-2012
	Веб-cайт разработчиков: http://aion-knight.ru
	=============================================
	Редакция: 20/12/2011 (Frost)
	
 -->
<player_experience_table 
	
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="player_experience_table.xsd">
	
	<exp>0</exp> <!-- Уровень 0 --> 
	<exp>650</exp> 
	<exp>2567</exp> 
	<exp>6797</exp> 
	<exp>15490</exp> 
	<exp>30073</exp> 
	<exp>52958</exp> 
	<exp>87894</exp> 
	<exp>140329</exp>
	<exp>213454</exp>
	<exp>307558</exp> <!-- Уровень 10 -->
	<exp>438553</exp> 
	<exp>608161</exp> 
	<exp>825336</exp> 
	<exp>1091985</exp>
	<exp>1418170</exp>
	<exp>1810467</exp>
	<exp>2332547</exp>
	<exp>3002260</exp>
	<exp>3820082</exp>
	<exp>4820229</exp> <!-- Уровень 20 -->
	<exp>6055323</exp> 
	<exp>7665200</exp> 
	<exp>9667124</exp> 
	<exp>12015782</exp>
	<exp>14702523</exp>
	<exp>17819939</exp>
	<exp>21422200</exp>
	<exp>25434736</exp>
	<exp>30111208</exp>
	<exp>35939440</exp> <!-- Уровень 30 -->
	<exp>42747682</exp>
	<exp>50838806</exp>
	<exp>60528213</exp>
	<exp>73197342</exp>
	<exp>89321807</exp>
	<exp>109063829</exp> 
	<exp>135085670</exp> 
	<exp>165021833</exp> 
	<exp>201169803</exp> 
	<exp>243343723</exp> <!-- Уровень 40 -->
	<exp>292699203</exp> 
	<exp>350659083</exp> 
	<exp>415031452</exp> 
	<exp>485413854</exp> 
	<exp>559280864</exp> 
	<exp>643809037</exp> 
	<exp>741317548</exp> 
	<exp>853743989</exp> 
	<exp>982653882</exp> 
	<exp>1128723910</exp> <!-- Уровень 50 -->
	<exp>1274793938</exp> 
	<exp>1452258716</exp>
	<exp>1656513717</exp>  
	<exp>1892999481</exp>  
	<exp>2164391835</exp> 
	<exp>2398328592</exp> 
	<exp>2696122834</exp> 
	<exp>3026674442</exp> 
	<exp>3393586726</exp> 
	<exp>3800859361</exp> <!-- Уровень 60 -->
</player_experience_table>
